namespace: kred
name: hashicorp
version: 1.0.0

description: HashiCorp Application Deployments
authors: ["Rune Rønneseth <rune.ronneseth@kred.no>"]

readme: README.md
license_file: LICENSE
dependencies: {}

repository: https://github.com/kred-no/ansible-collection-hashicorp
documentation: https://github.com/kred-no/ansible-collection-hashicorp
homepage: https://github.com/kred-no/ansible-collection-hashicorp
issues: https://github.com/kred-no/ansible-collection-hashicorp/issues

build_ignore:
  - extensions
  - molecule
  - tests

tags:
  - cni
  - consul
  - docker
  - hashicorp
  - nomad
  - vault
