# Role: CNI
cni_config:
  install: true
  version: '1.3.0'

# Role: HashiCluster
hashicluster_dns:
  forward: true

hashicluster_role:
  
  consul:
    install: true
    service:
      enabled: false
    config:
      data_dir: /opt/consul
      datacenter: dev-dc1
      client_addr: '0.0.0.0'
      recursors:
        - 1.1.1.1
        - 8.8.4.4
      retry_join:
        - mlc-server-1
      connect:
        enabled: true
      ui_config:
        enabled: false
      ports:
        grpc: 8502
      telemetry:
        prometheus_retention_time: 120s
  
  nomad:
    install: true
    service:
      enabled: false
    config:
      datacenter: dev-dc1
      data_dir: /opt/nomad
      #bind_addr: '0.0.0.0'
      client:
        enabled: true
        reserved:
          cpu: 100
          memory: 256
          disk: 500
        host_volume:
          ca-certificates:
            path: /etc/ssl/certs
            read_only: true
        options:
          driver.denylist: 'docker,qemu,raw_exec,exec,java'
          cgroups.enabled: false
      consul:
        address: 127.0.0.1:8500
        ssl: false
      telemetry:
        prometheus_metrics: true
        collection_interval: "10s"
        publish_allocation_metrics: true
        publish_node_metrics: true
  
  vault:
    install: false

supervisor_services:
  -
    name: consul
    bin_file: /usr/local/bin/consul
    cmd: consul agent -config-dir=/etc/consul.d
    state: present
  -
    name: nomad
    bin_file: /usr/local/bin/nomad
    cmd: nomad agent -config=/etc/nomad.d
    state: present
