docker_service_state: stopped

#cni_config:
#  install: true
#  version: '1.0.0'

hashicluster_dns:
  forward: true # NOTE: Requires --privileged container

hashicluster_role:
  
  consul:
    install: true
    service:
      enabled: false
    config:
      datacenter: dev-dc1
      data_dir: /opt/consul
      server: true
      bootstrap_expect: 1
      client_addr: "0.0.0.0"
      performance:
        raft_multiplier: 10
      recursors:
        - 1.1.1.1
        - 8.8.4.4
      connect:
        enabled: true
      ui_config:
        enabled: true
      ports:
        grpc: 8502

  nomad:
    install: true
    service:
      enabled: false
    config:
      datacenter: dev-dc1
      data_dir: /opt/nomad
      server:
        enabled: true
        bootstrap_expect: 1
      consul:
        address: 127.0.0.1:8500
        ssl: false

supervisor_services:
  -
    name: consul
    bin_file: /usr/local/bin/consul
    cmd: consul agent -config-dir=/etc/consul.d
    state: present
  -
    name: nomad
    bin_file: /usr/local/bin/nomad
    cmd: nomad agent -config=/etc/nomad.d
    state: present
