-
  name: DNS | Enable forwarding (PREROUTING)
  become: true
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    protocol: "{{ item }}"
    match: "{{ item }}"
    destination_port: '53'
    jump: REDIRECT
    to_ports: "{{ hashicluster_dns_merged['target_port'] }}"
    comment: "[HashiCluster] DNS rule ({{ item }})"
  loop:
    - tcp
    - udp
-
  name: DNS | Enable forwarding (OUTPUT)
  become: true
  ansible.builtin.iptables:
    table: nat
    chain: OUTPUT
    protocol: "{{ item }}"
    match: "{{ item }}"
    destination: localhost
    destination_port: '53'
    jump: REDIRECT
    to_ports: "{{ hashicluster_dns_merged['target_port'] }}"
    comment: "[HashiCluster] DNS rule ({{ item }})"
  loop:
    - tcp
    - udp
