-
  name: Validation
  when: # Stop the play if OS is NOT Debian or RedHat, unless 'force_install' is true
    -
      ansible_os_family | lower not in ['debian', 'redhat']
    -
      not (force_install | default(false))
  block:
    -
      name: OS Family Validation
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }} is not supported"
    -
      name: OS Family Validation Failed
      ansible.builtin.meta: end_play
-
  name: Application installation
  ansible.builtin.include_tasks: "_install_{{ ansible_os_family | lower }}.yml"
-
  name: Application configuration
  ansible.builtin.include_tasks: _settings.yml
-
  name: IP-tables forwarding (dns)
  ansible.builtin.include_tasks: _dns.yml
  when:
    - hashicluster_dns_merged['forward']
-
  name: Systemd unit/services
  ansible.builtin.include_tasks: _systemd.yml
  when: ansible_service_mgr == 'systemd'
-
  name: Flush handlers
  ansible.builtin.meta: flush_handlers
