# APPLICATION OVERRIDE VALUES
# See 'vars' for default values
---
# ===========================
# EXAMPLE CONFIG
# ===========================
#  cni:
#    install: true
cni_config: {}

# Try to install even if OS is not supported
cni_force_install: false
