-
  name: Create container instances
  hosts: localhost
  gather_facts: false
  #become: true

  tasks:
    -
      name: Build Container Images
      containers.podman.podman_image:
        name: local/{{ item }}:molecule
        state: present
        path: "{{ playbook_dir }}/"
        build:
          format: docker
          file: "{{ playbook_dir }}/Dockerfile.{{ item }}"
      loop:
        - ubuntu
    - name: Create network (dns resolution)
      containers.podman.podman_network:
        name: molecule_network
        state: present
    -
      name: Create Containers (Server)
      containers.podman.podman_container:
        image: "{{ hostvars[item]['container_image'] }}"
        name: "{{ item }}"
        hostname: "{{ item }}"
        network: molecule_network
        command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"] #sleep 1d
        privileged: true # Required for iptables update
        systemd: true
        log_driver: json-file
        state: started
      register: result
      loop: "{{ groups['server'] }}"
    -
      name: Create Containers (Client)
      containers.podman.podman_container:
        image: "{{ hostvars[item]['container_image'] }}"
        name: "{{ item }}"
        hostname: "{{ item }}"
        network: molecule_network
        command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"] #sleep 1d
        privileged: true # Required for iptables update
        systemd: true
        log_driver: json-file
        state: started
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      register: result
      loop: "{{ groups['client'] }}"
    -
      name: Wait for container to be ready
      ansible.builtin.wait_for_connection:
        timeout: 30
      delegate_to: "{{ item }}"
      loop: "{{ groups['molecule'] }}"
