FROM docker.io/ubuntu:latest

USER root

ENV DEBIAN_FRONTEND=noninteractive \
    container=podman

RUN set -e \
  && apt-get update \
  && apt-get -y install \
    python3 sudo dumb-init supervisor \
    iputils-ping iproute2 curl \
  && apt-get clean

#RUN set -e \
#  && apt-get update \
#  && apt-get -y install python3 python3-pip python3-venv \
#  && apt-get clean \
#  && python -m pip install pip --upgrade \
#  && python -m pip install supervisor --upgrade

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "-n"]
