- name: SYSTEMD | Start service
  become: true
  ansible.builtin.systemd:
    name: docker
    state: "{{ docker_service_state | default('started') }}"
    enabled: true
    masked: false
  notify:
    - systemd_reload
    - systemd_restart
