-
  name: Validation
  when:
    - ansible_os_family | lower != 'debian'
    - not docker_force_install | default(false)
  block:
    -
      name: OS Family Validation
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }} is not supported"
    -
      name: OS Family Validation Failed
      ansible.builtin.meta: end_play
-
  name: Manage Installation
  ansible.builtin.include_tasks: "_install_{{ ansible_os_family | lower }}.yml"
-
  name: Manage systemd unit/services
  ansible.builtin.include_tasks: _systemd.yml
  when: ansible_service_mgr == 'systemd'
-
  name: Flush handlers
  ansible.builtin.meta: flush_handlers
