# Configuration defaults.
---
# Defaults: HashiCorp applications settings
hashicluster_role_defaults:
  vault:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
  consul:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}
  nomad:
    install: false
    version: latest
    service:
      enabled: false
      masked: false
      user: root
    config: {}

# Defaults: DNS forwarding via iptables
hashicluster_dns_defaults:
  forward: false
  target_port: '8600'

# Combine defaults with overrides, for use in role tasks
hashicluster_role_merged: "{{ hashicluster_role_defaults | combine(hashicluster_role, recursive=true) }}"
hashicluster_dns_merged: "{{ hashicluster_dns_defaults | combine(hashicluster_dns, recursive=true) }}"
